baseURL: "https://frankccccc.github.io/hugo-PaperMod/"
languageCode: "en-us"
title: "Golden Hat"
theme: "papermod"

params:
    homeInfoParams:
        Title: Be Ambitious
        Content: Can be Info, links, about...

    socialIcons:
        - name: "FB"
          url: "<link>"
        - name: "<platform 2>"
          url: "<link2>"

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]