baseURL: "https://frankccccc.github.io/blog/"
languageCode: "en-us"
title: "Golden Hat"
theme: "papermod"

googleAnalytics: G-S9MCZ2NDS7
canonifyURLs: false
enableInlineShortcodes: true
paginate: 10
# paginatePath: "/page/"

enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false

# minify:
#     disableXML: true
#     minifyOutput: true

menu:
    main:
        - name: Search
          url: search/
          weight: 5
        - identifier: series
          name: Series
          url: series
          weight: 7
        - identifier: categories
          name: Categories
          url: categories/
          weight: 10
        - identifier: tags
          name: Tags
          url: tags/
          weight: 20

# Search Configs
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

# Catergory Configs
taxonomies:
    category: categories
    tag: tags
    series: series

params:
    env: production
    author: SY Chou
    defaultTheme: dark
    disableThemeToggle: false
    enableEmoji: true
    hidemeta: false
    ShowBreadCrumbs: true
    ShowReadingTime: true
    comments: true
    ShowPostNavLinks: true
    disableSpecial1stPost: false
    showtoc: false
    tocopen: false

    comment_light_theme: github-light
    comment_dark_theme: photon-dark

    label:
        text: "Golden Hat"
        icon: /blog/img/just_imgs/gold_empty_circle.svg
        iconHeight: 35

    homeInfoParams:
        Title: SY Chou's Blog
        Content: Then wear the gold hat, if that will move her; If you can bounce high, bounce for her too, Till she cry "Lover, gold-hatted, high-bouncing lover, I must have you!"  <<The Great Gatsby>>

    socialIcons:
        - name: "email"
          url: "mailto:quantumplanz@outlook.com"
        - name: "github"
          url: "https://github.com/FrankCCCCC"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/%E8%81%96%E8%AB%BA-%E5%91%A8-ba89b2184/"

    profileMode:
        enabled: false
        title: "SY Chou's Blog" # optional default will be site title
        subtitle: "Then wear the gold hat, if that will move her; If you can bounce high, bounce for her too, Till she cry 'Lover, gold-hatted, high-bouncing lover, I must have you!''  <<The Great Gatsby>>"
        # imageUrl: "<image link>" # optional
        imageTitle: "<title of image as alt>" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
          - name: Archive
            url: "/archive"
          - name: Github
            url: "https://github.com/"

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
    
    utter:
      enable: true
      repo: frankccccc/blog
      issueTerm: title
      # theme: github-light # Same as defaultTheme automatically